name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # Required for pushing changes (read-only required for deployment)
  pages: write # Required for deployment
  id-token: write # Required for deployment
  actions: read # Required for deployment

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install webp compression tool
        run: sudo apt-get install -y webp

      - name: Setup git config
        run: |
          git config --global user.name "skedwards88"
          git config --global user.email "skedwards88@gmail.com"

      - name: Bump version
        run: npm version patch

      - name: Push
        run: |
          git push origin main

      - name: Install requirements
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
